<a href="https://colab.research.google.com/github/sheshrajPawar/Activity_Detection/blob/main/datapreprocessing_45.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:

df=pd.read_csv('/Fraud.csv')

In [9]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
627839,34,CASH_OUT,181122.71,C651585324,56404.0,0.00,C317509232,0.00,181122.71,0.0,0.0
627840,34,PAYMENT,5412.56,C415515195,1062.0,0.00,M1995069219,0.00,0.00,0.0,0.0
627841,34,CASH_OUT,95385.70,C1170559510,9269.0,0.00,C1427089316,27051.23,122436.93,0.0,0.0
627842,34,PAYMENT,1116.95,C1354740357,8097.0,6980.05,M1783686963,0.00,0.00,0.0,0.0
627843,34,TRANSFER,1911467.49,C1319626261,8214.0,0.00,C1756573049,545108.00,NaN,NaN,NaN

In [10]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [11]:
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
627839,34,CASH_OUT,181122.71,C651585324,56404.0,0.00,C317509232,0.00,181122.71,0.0,0.0
627840,34,PAYMENT,5412.56,C415515195,1062.0,0.00,M1995069219,0.00,0.00,0.0,0.0
627841,34,CASH_OUT,95385.70,C1170559510,9269.0,0.00,C1427089316,27051.23,122436.93,0.0,0.0
627842,34,PAYMENT,1116.95,C1354740357,8097.0,6980.05,M1783686963,0.00,0.00,0.0,0.0
627843,34,TRANSFER,1911467.49,C1319626261,8214.0,0.00,C1756573049,545108.00,NaN,NaN,NaN

In [12]:
df.isnull()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
627839,False,False,False,False,False,False,False,False,False,False,False
627840,False,False,False,False,False,False,False,False,False,False,False
627841,False,False,False,False,False,False,False,False,False,False,False
627842,False,False,False,False,False,False,False,False,False,False,False
627843,False,False,False,False,False,False,False,False,True,True,True

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 627844 entries, 0 to 627843
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   step            627844 non-null  int64
 1   type            627844 non-null  object
 2   amount          627844 non-null  float64
 3   nameOrig        627844 non-null  object
 4   oldbalanceOrg   627844 non-null  float64
 5   newbalanceOrig  627844 non-null  float64
 6   nameDest        627844 non-null  object
 7   oldbalanceDest  627844 non-null  float64
 8   newbalanceDest  627843 non-null  float64
 9   isFraud         627843 non-null  float64
 10  isFlaggedFraud  627843 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 52.7+ MB

In [ ]:
df.mean()

In [ ]:
df.count()

In [15]:
df.count

<bound method DataFrame.count of         step      type      amount     nameOrig  oldbalanceOrg  \
0          1   PAYMENT     9839.64  C1231006815       170136.0
1          1   PAYMENT     1864.28  C1666544295        21249.0
2          1  TRANSFER      181.00  C1305486145          181.0
3          1  CASH_OUT      181.00   C840083671          181.0
4          1   PAYMENT    11668.14  C2048537720        41554.0
...      ...       ...         ...          ...            ...
627839    34  CASH_OUT   181122.71   C651585324        56404.0
627840    34   PAYMENT     5412.56   C415515195         1062.0
627841    34  CASH_OUT    95385.70  C1170559510         9269.0
627842    34   PAYMENT     1116.95  C1354740357         8097.0
627843    34  TRANSFER  1911467.49  C1319626261         8214.0

        newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0            160296.36  M1979787155            0.00            0.00      0.0
1             19384.72  M2044282225            0.00            0.00      0.0
2                 0.00   C553264065            0.00            0.00      1.0
3                 0.00    C38997010        21182.00            0.00      1.0
4             29885.86  M1230701703            0.00            0.00      0.0
...                ...          ...             ...             ...      ...
627839            0.00   C317509232            0.00       181122.71      0.0
627840            0.00  M1995069219            0.00            0.00      0.0
627841            0.00  C1427089316        27051.23       122436.93      0.0
627842         6980.05  M1783686963            0.00            0.00      0.0
627843            0.00  C1756573049       545108.00             NaN      NaN

        isFlaggedFraud
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0
...                ...
627839             0.0
627840             0.0
627841             0.0
627842             0.0
627843             NaN

[627844 rows x 11 columns]>

In [17]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [19]:
df.isFlaggedFraud

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
627839    0.0
627840    0.0
627841    0.0
627842    0.0
627843    NaN
Name: isFlaggedFraud, Length: 627844, dtype: float64

In [20]:
df.add_prefix

<bound method NDFrame.add_prefix of         step      type      amount     nameOrig  oldbalanceOrg  \
0          1   PAYMENT     9839.64  C1231006815       170136.0
1          1   PAYMENT     1864.28  C1666544295        21249.0
2          1  TRANSFER      181.00  C1305486145          181.0
3          1  CASH_OUT      181.00   C840083671          181.0
4          1   PAYMENT    11668.14  C2048537720        41554.0
...      ...       ...         ...          ...            ...
627839    34  CASH_OUT   181122.71   C651585324        56404.0
627840    34   PAYMENT     5412.56   C415515195         1062.0
627841    34  CASH_OUT    95385.70  C1170559510         9269.0
627842    34   PAYMENT     1116.95  C1354740357         8097.0
627843    34  TRANSFER  1911467.49  C1319626261         8214.0

        newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0            160296.36  M1979787155            0.00            0.00      0.0
1             19384.72  M2044282225            0.00            0.00      0.0
2                 0.00   C553264065            0.00            0.00      1.0
3                 0.00    C38997010        21182.00            0.00      1.0
4             29885.86  M1230701703            0.00            0.00      0.0
...                ...          ...             ...             ...      ...
627839            0.00   C317509232            0.00       181122.71      0.0
627840            0.00  M1995069219            0.00            0.00      0.0
627841            0.00  C1427089316        27051.23       122436.93      0.0
627842         6980.05  M1783686963            0.00            0.00      0.0
627843            0.00  C1756573049       545108.00             NaN      NaN

        isFlaggedFraud
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0
...                ...
627839             0.0
627840             0.0
627841             0.0
627842             0.0
627843             NaN

[627844 rows x 11 columns]>

In [21]:
df.all

<bound method NDFrame._add_numeric_operations.<locals>.all of         step      type      amount     nameOrig  oldbalanceOrg  \
0          1   PAYMENT     9839.64  C1231006815       170136.0
1          1   PAYMENT     1864.28  C1666544295        21249.0
2          1  TRANSFER      181.00  C1305486145          181.0
3          1  CASH_OUT      181.00   C840083671          181.0
4          1   PAYMENT    11668.14  C2048537720        41554.0
...      ...       ...         ...          ...            ...
627839    34  CASH_OUT   181122.71   C651585324        56404.0
627840    34   PAYMENT     5412.56   C415515195         1062.0
627841    34  CASH_OUT    95385.70  C1170559510         9269.0
627842    34   PAYMENT     1116.95  C1354740357         8097.0
627843    34  TRANSFER  1911467.49  C1319626261         8214.0

        newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0            160296.36  M1979787155            0.00            0.00      0.0
1             19384.72  M2044282225            0.00            0.00      0.0
2                 0.00   C553264065            0.00            0.00      1.0
3                 0.00    C38997010        21182.00            0.00      1.0
4             29885.86  M1230701703            0.00            0.00      0.0
...                ...          ...             ...             ...      ...
627839            0.00   C317509232            0.00       181122.71      0.0
627840            0.00  M1995069219            0.00            0.00      0.0
627841            0.00  C1427089316        27051.23       122436.93      0.0
627842         6980.05  M1783686963            0.00            0.00      0.0
627843            0.00  C1756573049       545108.00             NaN      NaN

        isFlaggedFraud
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0
...                ...
627839             0.0
627840             0.0
627841             0.0
627842             0.0
627843             NaN

[627844 rows x 11 columns]>

In [22]:
df.bool

<bound method NDFrame.bool of         step      type      amount     nameOrig  oldbalanceOrg  \
0          1   PAYMENT     9839.64  C1231006815       170136.0
1          1   PAYMENT     1864.28  C1666544295        21249.0
2          1  TRANSFER      181.00  C1305486145          181.0
3          1  CASH_OUT      181.00   C840083671          181.0
4          1   PAYMENT    11668.14  C2048537720        41554.0
...      ...       ...         ...          ...            ...
627839    34  CASH_OUT   181122.71   C651585324        56404.0
627840    34   PAYMENT     5412.56   C415515195         1062.0
627841    34  CASH_OUT    95385.70  C1170559510         9269.0
627842    34   PAYMENT     1116.95  C1354740357         8097.0
627843    34  TRANSFER  1911467.49  C1319626261         8214.0

        newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0            160296.36  M1979787155            0.00            0.00      0.0
1             19384.72  M2044282225            0.00            0.00      0.0
2                 0.00   C553264065            0.00            0.00      1.0
3                 0.00    C38997010        21182.00            0.00      1.0
4             29885.86  M1230701703            0.00            0.00      0.0
...                ...          ...             ...             ...      ...
627839            0.00   C317509232            0.00       181122.71      0.0
627840            0.00  M1995069219            0.00            0.00      0.0
627841            0.00  C1427089316        27051.23       122436.93      0.0
627842         6980.05  M1783686963            0.00            0.00      0.0
627843            0.00  C1756573049       545108.00             NaN      NaN

        isFlaggedFraud
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0
...                ...
627839             0.0
627840             0.0
627841             0.0
627842             0.0
627843             NaN

[627844 rows x 11 columns]>

In [23]:
df.convert_dtypes

<bound method NDFrame.convert_dtypes of         step      type      amount     nameOrig  oldbalanceOrg  \
0          1   PAYMENT     9839.64  C1231006815       170136.0
1          1   PAYMENT     1864.28  C1666544295        21249.0
2          1  TRANSFER      181.00  C1305486145          181.0
3          1  CASH_OUT      181.00   C840083671          181.0
4          1   PAYMENT    11668.14  C2048537720        41554.0
...      ...       ...         ...          ...            ...
627839    34  CASH_OUT   181122.71   C651585324        56404.0
627840    34   PAYMENT     5412.56   C415515195         1062.0
627841    34  CASH_OUT    95385.70  C1170559510         9269.0
627842    34   PAYMENT     1116.95  C1354740357         8097.0
627843    34  TRANSFER  1911467.49  C1319626261         8214.0

        newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0            160296.36  M1979787155            0.00            0.00      0.0
1             19384.72  M2044282225            0.00            0.00      0.0
2                 0.00   C553264065            0.00            0.00      1.0
3                 0.00    C38997010        21182.00            0.00      1.0
4             29885.86  M1230701703            0.00            0.00      0.0
...                ...          ...             ...             ...      ...
627839            0.00   C317509232            0.00       181122.71      0.0
627840            0.00  M1995069219            0.00            0.00      0.0
627841            0.00  C1427089316        27051.23       122436.93      0.0
627842         6980.05  M1783686963            0.00            0.00      0.0
627843            0.00  C1756573049       545108.00             NaN      NaN

        isFlaggedFraud
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0
...                ...
627839             0.0
627840             0.0
627841             0.0
627842             0.0
627843             NaN

[627844 rows x 11 columns]>

In [24]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of         step      type      amount     nameOrig  oldbalanceOrg  \
0          1   PAYMENT     9839.64  C1231006815       170136.0
1          1   PAYMENT     1864.28  C1666544295        21249.0
2          1  TRANSFER      181.00  C1305486145          181.0
3          1  CASH_OUT      181.00   C840083671          181.0
4          1   PAYMENT    11668.14  C2048537720        41554.0
...      ...       ...         ...          ...            ...
627839    34  CASH_OUT   181122.71   C651585324        56404.0
627840    34   PAYMENT     5412.56   C415515195         1062.0
627841    34  CASH_OUT    95385.70  C1170559510         9269.0
627842    34   PAYMENT     1116.95  C1354740357         8097.0
627843    34  TRANSFER  1911467.49  C1319626261         8214.0

        newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0            160296.36  M1979787155            0.00            0.00      0.0
1             19384.72  M2044282225            0.00            0.00      0.0
2                 0.00   C553264065            0.00            0.00      1.0
3                 0.00    C38997010        21182.00            0.00      1.0
4             29885.86  M1230701703            0.00            0.00      0.0
...                ...          ...             ...             ...      ...
627839            0.00   C317509232            0.00       181122.71      0.0
627840            0.00  M1995069219            0.00            0.00      0.0
627841            0.00  C1427089316        27051.23       122436.93      0.0
627842         6980.05  M1783686963            0.00            0.00      0.0
627843            0.00  C1756573049       545108.00             NaN      NaN

        isFlaggedFraud
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0
...                ...
627839             0.0
627840             0.0
627841             0.0
627842             0.0
627843             NaN

[627844 rows x 11 columns]>

In [29]:
column10_duplicates=df.drop_duplicates("isFraud")

In [30]:
column10_duplicates

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
627843,34,TRANSFER,1911467.49,C1319626261,8214.0,0.00,C1756573049,545108.0,NaN,NaN,NaN

In [31]:
colummn11_duplicates=df.drop_duplicates("isFlaggedFraud")

In [32]:
colummn11_duplicates

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
627843,34,TRANSFER,1911467.49,C1319626261,8214.0,0.00,C1756573049,545108.0,NaN,NaN,NaN

In [33]:
column10_duplicates=df.drop_duplicates("newbalanceDest")

In [34]:
column10_duplicates

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0.0,0.0
9,1,DEBIT,5337.77,C712410124,41720.0,36382.23,C195600860,41898.00,40348.79,0.0,0.0
10,1,DEBIT,9644.94,C1900366749,4465.0,0.00,C997608398,10845.00,157982.12,0.0,0.0
15,1,CASH_OUT,229133.94,C905080434,15325.0,0.00,C476402209,5083.00,51513.44,0.0,0.0
21,1,DEBIT,9302.79,C1566511282,11299.0,1996.21,C1973538135,29832.00,16896.70,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
627836,34,CASH_OUT,71502.29,C1640594013,202393.0,130890.71,C476112429,149720.81,221223.10,0.0,0.0
627837,34,TRANSFER,453962.90,C776080832,31.0,0.00,C762277956,838214.27,1292177.17,0.0,0.0
627839,34,CASH_OUT,181122.71,C651585324,56404.0,0.00,C317509232,0.00,181122.71,0.0,0.0
627841,34,CASH_OUT,95385.70,C1170559510,9269.0,0.00,C1427089316,27051.23,122436.93,0.0,0.0
627843,34,TRANSFER,1911467.49,C1319626261,8214.0,0.00,C1756573049,545108.00,NaN,NaN,NaN

In [35]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
627839,34,CASH_OUT,181122.71,C651585324,56404.0,0.00,C317509232,0.00,181122.71,0.0,0.0
627840,34,PAYMENT,5412.56,C415515195,1062.0,0.00,M1995069219,0.00,0.00,0.0,0.0
627841,34,CASH_OUT,95385.70,C1170559510,9269.0,0.00,C1427089316,27051.23,122436.93,0.0,0.0
627842,34,PAYMENT,1116.95,C1354740357,8097.0,6980.05,M1783686963,0.00,0.00,0.0,0.0
627843,34,TRANSFER,1911467.49,C1319626261,8214.0,0.00,C1756573049,545108.00,NaN,NaN,NaN

In [42]:
df.dropna

<bound method DataFrame.dropna of         step      type      amount     nameOrig  oldbalanceOrg  \
0          1   PAYMENT     9839.64  C1231006815       170136.0
1          1   PAYMENT     1864.28  C1666544295        21249.0
2          1  TRANSFER      181.00  C1305486145          181.0
3          1  CASH_OUT      181.00   C840083671          181.0
4          1   PAYMENT    11668.14  C2048537720        41554.0
...      ...       ...         ...          ...            ...
627839    34  CASH_OUT   181122.71   C651585324        56404.0
627840    34   PAYMENT     5412.56   C415515195         1062.0
627841    34  CASH_OUT    95385.70  C1170559510         9269.0
627842    34   PAYMENT     1116.95  C1354740357         8097.0
627843    34  TRANSFER  1911467.49  C1319626261         8214.0

        newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0            160296.36  M1979787155            0.00            0.00      0.0
1             19384.72  M2044282225            0.00            0.00      0.0
2                 0.00   C553264065            0.00            0.00      1.0
3                 0.00    C38997010        21182.00            0.00      1.0
4             29885.86  M1230701703            0.00            0.00      0.0
...                ...          ...             ...             ...      ...
627839            0.00   C317509232            0.00       181122.71      0.0
627840            0.00  M1995069219            0.00            0.00      0.0
627841            0.00  C1427089316        27051.23       122436.93      0.0
627842         6980.05  M1783686963            0.00            0.00      0.0
627843            0.00  C1756573049       545108.00             NaN      NaN

        isFlaggedFraud
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0
...                ...
627839             0.0
627840             0.0
627841             0.0
627842             0.0
627843             NaN

[627844 rows x 11 columns]>

In [44]:
df.dropna(subset=["isFraud"])

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
627838,34,PAYMENT,14672.30,C1576429270,36705.0,22032.70,M208142191,0.00,0.00,0.0,0.0
627839,34,CASH_OUT,181122.71,C651585324,56404.0,0.00,C317509232,0.00,181122.71,0.0,0.0
627840,34,PAYMENT,5412.56,C415515195,1062.0,0.00,M1995069219,0.00,0.00,0.0,0.0
627841,34,CASH_OUT,95385.70,C1170559510,9269.0,0.00,C1427089316,27051.23,122436.93,0.0,0.0
627842,34,PAYMENT,1116.95,C1354740357,8097.0,6980.05,M1783686963,0.00,0.00,0.0,0.0

In [45]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [46]:
df.dropna(thresh=0.8, axis=1, inplace=True)

In [49]:
df["outlier"] = 0

In [50]:
# Calculate Q1, Q2, Q3
Q1 = df["amount"].quantile(0.25)
Q2 = df["amount"].quantile(0.5)
Q3 = df["amount"].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Identify outliers
df["outlier"] = np.where(
    (df["amount"] < Q1 - 1.5 * IQR) | (df["amount"] > Q3 + 1.5 * IQR),
    1,
    0,
)

In [51]:
missing_values = df.isnull().sum()

# Print the number of missing values in each column
print(missing_values)

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
outlier           0
dtype: int64

In [53]:
# Drop columns with a high percentage of missing values
df.dropna(thresh=0.8, axis=1, inplace=True)

# Impute missing values in remaining columns
df["isFlaggedFraud"].fillna(df["isFlaggedFraud"].mean(), inplace=True)

In [55]:
# Drop columns with a high percentage of missing values
df.dropna(thresh=0.8, axis=1, inplace=True)

# Impute missing values in remaining columns
df["newbalanceDest"].fillna(df["newbalanceDest"].mean(), inplace=True)

In [56]:
# Drop columns with a high percentage of missing values
df.dropna(thresh=0.8, axis=1, inplace=True)

# Impute missing values in remaining columns
df["isFraud"].fillna(df["isFraud"].mean(), inplace=True)

In [59]:
df["type"] = df["type"].astype("str")

In [60]:
df["type"] = df["type"].replace("CASH_IN", 0)

In [62]:
df["type"] = df["type"].astype("str")

In [63]:
df["type"] = df["type"].replace("PAYMENT", 0)

In [65]:
df["type"] = df["type"].astype("str")
df["type"] = df["type"].replace("TRANSFER", 0)

In [68]:
df["type"] = df["type"].astype("str")
df["type"] = df["type"].replace("CASH_OUT", 0)

In [ ]:

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Load the data
df = pd.read_csv("/Fraud.csv")

# Preprocess the data
df.dropna(inplace=True)
df["outliers"] = np.where(
    (df["amount"] < Q1 - 1.5 * IQR) | (df["amount"] > Q3 + 1.5 * IQR),
    1,
    0,
)

# Split the data into training and testing sets
X = df.drop(["isFraud", "outliers"], axis=1)
y = df["isFraud"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

In [71]:

df = pd.read_csv("/Fraud.csv")

# Calculate correlation between each variable and the target variable
correlations = df.corr()["isFraud"]

# Select variables with a strong correlation with the target variable
selected_variables = correlations[abs(correlations) > 0.5].index.tolist()

<ipython-input-71-2f178dbfbd22>:6: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlations = df.corr()["isFraud"]

In [72]:
# Examine the relationship between pairs of variables
for i in selected_variables:
    for j in selected_variables:
        if i != j:
            sns.scatterplot(x=df[i], y=df[j])
            plt.show()

In [75]:


df = pd.read_csv("/Fraud.csv")

# Select features for the model
selected_features = ["amount", "oldbalanceOrg", "newbalanceOrig", "oldbalanceDest", "newbalanceDest"]

# Define X and y
X = df[selected_features]
y = df["isFraud"]

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Build a model using the selected variables
X = df[selected_variables]
y = df["isFraud"]

model = RandomForestClassifier()
model.fit(X, y)

# Evaluate the model
y_pred = model.predict(X)

from sklearn.metrics import classification_report

print(classification_report(y, y_pred))

In [77]:
mse = (y_test-y_train)**2
print(f"MSE: {mse.mean():0.2f} (+/- {mse.std():0.2f})")

MSE: nan (+/- nan)

In [78]:
mae = np.abs(y_test-y_train)
print(f"MAE: {mae.mean():0.2f} (+/- {mae.std():0.2f})")

MAE: nan (+/- nan)

In [79]:
mse = (y_test-y_train)**2
rmse = np.sqrt(mse.mean())
print(f"RMSE: {rmse:0.2f}")

RMSE: nan

In [ ]:


df = pd.read_csv("/Fraud.csv")

# Select features for the model
selected_features = ["amount", "oldbalanceOrg", "newbalanceOrig", "oldbalanceDest", "newbalanceDest"]

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X = df[selected_features]
y = df["isFraud"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a model
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

# Get feature importances
importances = model.feature_importances_

# Create a dataframe of feature importances
feature_importances = pd.DataFrame({"feature": selected_features, "importance": importances})

# Sort features by importance
feature_importances = feature_importances.sort_values("importance", ascending=False)

# Print the key factors
print("Key factors that predict fraudulent customers:")
print(feature_importances["feature"].head())